version: 0.2

env:
  parameter-store:
    VITE_FIREBASE_API_KEY: "/toycars/dev/frontend/VITE_FIREBASE_API_KEY"
    VITE_FIREBASE_APP_ID: "/toycars/dev/frontend/VITE_FIREBASE_APP_ID"
    VITE_FIREBASE_AUTH_DOMAIN: "/toycars/dev/frontend/VITE_FIREBASE_AUTH_DOMAIN"
    VITE_FIREBASE_MEASUREMENT_ID: "/toycars/dev/frontend/VITE_FIREBASE_MEASUREMENT_ID"
    VITE_FIREBASE_MESSAGING_SENDER_ID: "/toycars/dev/frontend/VITE_FIREBASE_MESSAGING_SENDER_ID"
    VITE_FIREBASE_PROJECT_ID: "/toycars/dev/frontend/VITE_FIREBASE_PROJECT_ID"
    VITE_FIREBASE_STORAGE_BUCKET: "/toycars/dev/frontend/VITE_FIREBASE_STORAGE_BUCKET"
    VITE_FIRESTORE_REQ_BODY_NAME: "/toycars/dev/frontend/VITE_FIRESTORE_REQ_BODY_NAME"
    VITE_FIRESTORE_USER_PROFILES_BASE_URL: "/toycars/dev/frontend/VITE_FIRESTORE_USER_PROFILES_BASE_URL"
    VITE_GOOGLE_CLIENT_ID: "/toycars/dev/frontend/VITE_GOOGLE_CLIENT_ID"
    VITE_RECAPTCHA_V3_SITE_KEY: "/toycars/dev/frontend/VITE_RECAPTCHA_V3_SITE_KEY"
    VITE_BACKEND_ENDPOINT: "/toycars/dev/frontend/VITE_BACKEND_ENDPOINT"
phases:
  pre_build:
    commands:
      - |
        if [ -z "$VITE_FIREBASE_API_KEY" ]; then
          echo "VITE_FIREBASE_API_KEY is not set"
        else
          echo "VITE_FIREBASE_API_KEY is set"
        fi
      - |
        if [ -z "$VITE_FIREBASE_APP_ID" ]; then
          echo "VITE_FIREBASE_APP_ID is not set"
        else
          echo "VITE_FIREBASE_APP_ID is set"
        fi
      - echo "VITE_FIREBASE_API_KEY $VITE_FIREBASE_API_KEY"
      - echo "VITE_FIREBASE_APP_ID $VITE_FIREBASE_APP_ID"
      - echo "VITE_FIREBASE_AUTH_DOMAIN $VITE_FIREBASE_AUTH_DOMAIN"
      - echo "VITE_FIREBASE_MEASUREMENT_ID $VITE_FIREBASE_MEASUREMENT_ID"
      - echo "VITE_FIREBASE_MESSAGING_SENDER_ID $VITE_FIREBASE_MESSAGING_SENDER_ID"
      - echo "VITE_FIREBASE_PROJECT_ID $VITE_FIREBASE_PROJECT_ID"
      - echo "VITE_FIREBASE_STORAGE_BUCKET $VITE_FIREBASE_STORAGE_BUCKET"
      - echo "VITE_FIRESTORE_REQ_BODY_NAME $VITE_FIRESTORE_REQ_BODY_NAME"
      - echo "VITE_FIRESTORE_USER_PROFILES_BASE_URL $VITE_FIRESTORE_USER_PROFILES_BASE_URL"
      - echo "VITE_GOOGLE_CLIENT_ID $VITE_GOOGLE_CLIENT_ID"
      - echo "VITE_RECAPTCHA_V3_SITE_KEY $VITE_RECAPTCHA_V3_SITE_KEY"
      - echo "VITE_BACKEND_ENDPOINT $VITE_BACKEND_ENDPOINT"
      - echo Build started on `date`
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building the Docker image ...
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG .
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image ...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
