export const WISHLIST_ACTION_TYPES = {
  TOGGLE_WISHLIST_START: "wishlist/TOGGLE_WISHLIST_START",
  TOGGLE_WISHLIST_ERROR: "wishlist/TOGGLE_WISHLIST_ERROR",
  FETCH_WISHLIST_START: "wishlist/FETCH_WISHLIST_START",
  FETCH_WISHLIST_ERROR: "wishlist/FETCH_WISHLIST_ERROR",
  FETCH_WISHLIST_SUCCESS: "wishlist/FETCH_WISHLIST_SUCCESS",
  CLEAR_WISHLIST_LOCAL: "wishlist/CLEAR_WISHLIST_LOCAL", // this is the thing to do when log out.
};
